spring.application.name=ebsa
server.port=8086
server.address=0.0.0.0

# Oracle SIEC
spring.datasource.url=jdbc:oracle:thin:@172.16.235.190:1521/siec
spring.datasource.username=siec
spring.datasource.password=Calidad_25 
spring.datasource.oracleucp.min-pool-size=5
spring.datasource.oracleucp.max-pool-size=15
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
# jwt.secret=ZmFrZXNlY3JldGtleWFuZG15b3RoZXJzZWNyZXRz
jwt.secret=klf8Fjd47shSkdl389dhFks7GHDsTytlDhkd7shshfhsh389dKF8shhdskjf7ghskdhskd

jwt.expiration=3600 

# Ruta configurada en application.properties
# app.file.directory=C:/Users/dperez.EBSA0/Downloads/Formato15p
# app.file.directory=//172.16.10.26/CREG Report Repository
# app.file.directory=C:/Users/usuario/Downloads/Formatos pruebas/prueba
# spring.mail.properties.mail.smtp.ssl.trust=10.189.235.232
